/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fis.poo.poli_cine.vista;

import fis.poo.poli_cine.modelo.CineGestor;
import fis.poo.poli_cine.modelo.Funcion;
import fis.poo.poli_cine.modelo.Horario;
import fis.poo.poli_cine.modelo.Pelicula;
import fis.poo.poli_cine.modelo.Sala;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import java.awt.Image;



/**
 *
 * @author sebas
 */
public class Vista1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista1.class.getName());
    //posdata con esta referencia se abre un poco el encapsulamiento pero puedo hacer referencia a la memoria del cinegestor instanciado
    
    CineGestor cinegestor1;
    DefaultListModel<String> modeloLogicoLista = new DefaultListModel<>();

    
    /**
     * Creates new form Vista1
     */
    public Vista1() {
        initComponents();
        
    }
    
    //este me sirve para el boton de siguiente
    public void avisarQueDebeEscogerFuncion(){
    jTextField1.setText("Escoge una funcion para continuar");
    }
    //este me sirve para el boton de siguiente
    public Boolean verificarSiEscogioFuncion(){
        if(jLabel1.getText().equals("")){
        return false;
        }
    return true;
    }
    
    public void listenerPasarASeleccionAsiento(java.awt.event.ActionListener accion){
    jButton3.addActionListener(accion);
    }
    
    public Funcion retornarInstanciadeFuncionEscogida(){
        String[] caracteristicas = jList1.getSelectedValue().split(",");
        for(Funcion a:cinegestor1.retornarListaFunciones()){
            if(a.retornarPelicula().retornarNombre().equals(caracteristicas[0])){
                if(a.retornarHorario().retornarHorario().equals(caracteristicas[1])){
                                            
                    System.out.println("Si se esta retornando una funcion");

                        return a;
                }
            
            }
        }
                                System.out.println("NO se esta retornando una funcion");

        return null;
    }
    
    public void renderizarFuncionEscogida(){
        
        for(Funcion rr: cinegestor1.retornarListaFunciones()){
            String[] caracteristicas = jList1.getSelectedValue().split(",");
            
            if(caracteristicas[0].equals(rr.retornarPelicula().retornarNombre())){
                
                jLabel1.setText(rr.retornarPelicula().retornarNombre());
                jTextField1.setText(rr.retornarPelicula().retornarDescripcion());
                
                ImageIcon imagen = new ImageIcon(rr.retornarPelicula().retornarRuta());
                int ancho = jLabel4.getWidth();
                int alto = jLabel4.getHeight();
                
                Image imagenEscalada = imagen.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                jLabel4.setIcon(new ImageIcon(imagenEscalada));
                     
            
            }
        }
        
    }
    
    public void mensajeNoSeleccionoNada(){
    jTextField1.setText("Selecciona una funcion para continuar");
    }
    
    public Boolean validarSiEstaEscogidoAlgo(){
        
        if(jList1.getSelectedValue()==null){
        return false;
        }else{
                    System.out.print("Si esta retornando true");

        return true;
        }
        
    }
    
    public void listenerSeleccionarFuncion(java.awt.event.ActionListener accion){
        btnSeleccionarPelicula.addActionListener(accion);
    }
    
    public void vaciarLista(){
    modeloLogicoLista.clear();
    jList1.setModel(modeloLogicoLista);
    }
    
    public void llenarListaVisual(){
        
        for(Funcion a:cinegestor1.retornarListaFunciones()){
            modeloLogicoLista.addElement(a.retornarPelicula().retornarNombre()+","+a.retornarHorario().retornarHorario());
        }
        jList1.setModel(modeloLogicoLista);  
    }
    
    
    
    public void recibirCineGestor(CineGestor cine){
    this.cinegestor1 = cine;
    }
    
    public void listenerAdministrador(java.awt.event.ActionListener accion){
    jButton1.addActionListener(accion);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSeleccionarPelicula = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Mono", 0, 24)); // NOI18N
        jLabel1.setOpaque(true);

        jButton1.setText("Administrador");

        jList1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Mono", 0, 24)); // NOI18N
        jLabel2.setText("PoliCine || Comprar Entradas");
        jLabel2.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Liberation Mono", 0, 24)); // NOI18N
        jLabel4.setOpaque(true);

        btnSeleccionarPelicula.setText("Seleccionar Pelicula");
        btnSeleccionarPelicula.addActionListener(this::btnSeleccionarPeliculaActionPerformed);

        jButton3.setText("Siguiente");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSeleccionarPelicula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeleccionarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarPeliculaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarPelicula;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
